/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ApproachRouteImport } from './routes/approach'
import { Route as CertificationRouteImport } from './routes/certification'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as PartnershipsRouteImport } from './routes/partnerships'
import { Route as ProjectsRouteImport } from './routes/projects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ApproachRoute = ApproachRouteImport.update({
  id: '/approach',
  path: '/approach',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificationRoute = CertificationRouteImport.update({
  id: '/certification',
  path: '/certification',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipsRoute = PartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/certification': typeof CertificationRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/partnerships': typeof PartnershipsRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/certification': typeof CertificationRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/partnerships': typeof PartnershipsRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/about': typeof AboutRoute
  '/approach': typeof ApproachRoute
  '/certification': typeof CertificationRoute
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/partnerships': typeof PartnershipsRoute
  '/projects': typeof ProjectsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/about'
    | '/approach'
    | '/certification'
    | '/community'
    | '/contact'
    | '/courses'
    | '/partnerships'
    | '/projects'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/about'
    | '/approach'
    | '/certification'
    | '/community'
    | '/contact'
    | '/courses'
    | '/partnerships'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/about'
    | '/approach'
    | '/certification'
    | '/community'
    | '/contact'
    | '/courses'
    | '/partnerships'
    | '/projects'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AboutRoute: typeof AboutRoute
  ApproachRoute: typeof ApproachRoute
  CertificationRoute: typeof CertificationRoute
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  PartnershipsRoute: typeof PartnershipsRoute
  ProjectsRoute: typeof ProjectsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approach': {
      id: '/approach'
      path: '/approach'
      fullPath: '/approach'
      preLoaderRoute: typeof ApproachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certification': {
      id: '/certification'
      path: '/certification'
      fullPath: '/certification'
      preLoaderRoute: typeof CertificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnerships': {
      id: '/partnerships'
      path: '/partnerships'
      fullPath: '/partnerships'
      preLoaderRoute: typeof PartnershipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AboutRoute: AboutRoute,
  ApproachRoute: ApproachRoute,
  CertificationRoute: CertificationRoute,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  PartnershipsRoute: PartnershipsRoute,
  ProjectsRoute: ProjectsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
